#!/bin/bash
# cf. http://www.mactricksandtips.com/2008/02/top-50-terminal-commands.html

usage() {
  echo "Usage: $(basename ${0}) white|grey"
  exit 1
}

if [[ ${#} -eq 0 ]]; then
  usage;
fi

if [[ ${EUID} -ne 0 ]]; then
  echo 'This script must be run as root.' 1>&2
  exit 1
fi

case "${1}" in
  grey)
    param=0
    ;;
  white)
    param=1
    ;;
  *)
    usage
esac

defaults write /System/Library/LaunchDaemons/com.apple.WindowServer \
  'EnvironmentVariables' -dict 'CI_NO_BACKGROUND_IMAGE' ${param}

echo 'This will take effect after a reboot.'

